app: coinc-ms-accounts
service: coinc-ms-accounts
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  timeout: 30

custom:
  # webpackIncludeModules: true
  esbuild:
    bundle: true
    minify: false
  serviceName: coinc-ms-accounts
  baseApi: ${self:custom.serviceName}
  handlers: src/frameworks/handlers

functions:
  getAccount:
    handler: ${self:custom.handlers}/getAccount.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{accountId}
          method: get
          cors:
            origin: '*'
            headers: '*'
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
